# AI4I 분할 v2 — AutoGluon 모델별 · 앙상블 조합별 비교

- 학습 = train, 고르기 = val(`score_val`), 마지막 확인 = test(`score_test`, 고를 때 보지 않음). demo 몫은 쓰지 않음
- 데이터: `../csv/ai4i-{train,val,test}.csv` (README 참고)
- 설치: 같은 폴더 `requirements.txt` (Python 3.12 가상환경 권장)

## 1. 설정

In [1]:
from itertools import combinations
from pathlib import Path

import pandas as pd
from autogluon.tabular import TabularPredictor

DATA = Path("../csv")        # 이 노트북이 examples/ 폴더에 있을 때
TARGET = "failure_type"      # "failure_type"(NONE · TWF · HDF · PWF · OSF) 또는 "Machine failure"(0/1)
ADD_FEATURES = True          # 온도 차 · 출력 칸을 더함(Pack도 같은 값을 계산함)
TIME_LIMIT = 600             # 초
TOP_K = 4                    # 조합을 만들 상위 모델 수(val 기준)

DROP = ["UDI", "Product ID", "Machine failure", "TWF", "HDF", "PWF", "OSF", "RNF"]
assert (DATA / "ai4i-train.csv").exists(), "DATA 경로를 csv 폴더로 맞춰 주세요"

## 2. 데이터 읽기 · 정답 칸 만들기

In [2]:
def load(name):
    df = pd.read_csv(DATA / f"ai4i-{name}.csv")
    if TARGET == "failure_type":
        # 한 행에 고장 유형이 둘 이상이면 TWF > HDF > PWF > OSF 순으로 하나(train 14행). RNF(무작위 고장)만 있는 행은 NONE
        df[TARGET] = "NONE"
        for t in ["OSF", "PWF", "HDF", "TWF"]:
            df.loc[df[t] == 1, TARGET] = t
    else:
        df[TARGET] = df["Machine failure"]
    if ADD_FEATURES:
        df["temp_diff_k"] = df["Process temperature [K]"] - df["Air temperature [K]"]
        df["power_w"] = df["Torque [Nm]"] * df["Rotational speed [rpm]"] * 2 * 3.141592653589793 / 60
    return df.drop(columns=[c for c in DROP if c != TARGET])


train, val, test = load("train"), load("val"), load("test")
pd.DataFrame({k: d[TARGET].value_counts() for k, d in [("train", train), ("val", val), ("test", test)]})

              train   val  test
failure_type
HDF              49    15    16
NONE           5561  1852  1855
OSF              46    17    15
PWF              53    19    19
TWF              26     9     9

## 3. 학습 (모델별)

In [3]:
metric = "f1_macro" if TARGET == "failure_type" else "f1"
predictor = TabularPredictor(
    label=TARGET,
    eval_metric=metric,
    sample_weight="balance_weight",   # 고장 행이 적어서 클래스 비율로 무게를 맞춤
    path="ag-ai4i",
).fit(
    train_data=train,
    tuning_data=val,
    presets="medium_quality",
    time_limit=TIME_LIMIT,
)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:30 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6020
CPU Count:          12
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.84 GB / 32.00 GB (21.4%)
Disk Space Avail:   169.37 GB / 926.35 GB (18.3%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Using predefined sample weighting strategy: balance_weight. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/insujo/Documents/repo/orchestration/data/ai4i-split-v2/examples/ag-ai4i"
Train Data Rows:    5735
Train Data Columns: 8
Tuning Data Rows:    1912
Tuning Data Columns: 8
Label Column:       failure_type
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	5 unique label values:  ['NONE', 'OSF', 'PWF', 'TWF', 'HDF']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data...
Assigning sample weights to balance differences in frequency of classes.
Train Data Class Count: 5
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6952.27 MB
	Train Data (Original)  Memory Usage: 0.77 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 5 | ['Air temperature [K]', 'Process temperature [K]', 'Torque [Nm]', 'temp_diff_k', 'power_w']
		('int', [])    : 2 | ['Rotational speed [rpm]', 'Tool wear [min]']
		('object', []) : 1 | ['Type']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['Type']
		('float', [])    : 5 | ['Air temperature [K]', 'Process temperature [K]', 'Torque [Nm]', 'temp_diff_k', 'power_w']
		('int', [])      : 2 | ['Rotational speed [rpm]', 'Tool wear [min]']
	0.0s = Fit runtime
	8 features in original data used to generate 8 features in processed data.
	Train Data (Processed) Memory Usage: 0.42 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1_macro'
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 599.95s of the 599.95s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.0/6.8 GB
Matplotlib is building the font cache; this may take a moment.
	0.7174	 = Validation score   (f1_macro)
	14.61s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 585.31s of the 585.31s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/6.0 GB
	0.6842	 = Validation score   (f1_macro)
	18.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 566.72s of the 566.71s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/6.1 GB
	0.7781	 = Validation score   (f1_macro)
	7.78s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 558.90s of the 558.90s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/6.0 GB
	0.717	 = Validation score   (f1_macro)
	3.03s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 555.81s of the 555.81s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/6.1 GB
	0.732	 = Validation score   (f1_macro)
	0.36s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 555.40s of the 555.40s of remaining time.
	Fitting with cpus=12, gpus=0
	0.7475	 = Validation score   (f1_macro)
	28.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 526.42s of the 526.42s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/6.0 GB
	0.689	 = Validation score   (f1_macro)
	0.38s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 525.98s of the 525.98s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/5.9 GB
	0.6826	 = Validation score   (f1_macro)
	0.35s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 525.57s of the 525.57s of remaining time.
	Fitting with cpus=12, gpus=0
	0.7996	 = Validation score   (f1_macro)
	2.36s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 523.20s of the 523.20s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.0/5.8 GB
	0.7318	 = Validation score   (f1_macro)
	22.66s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 500.53s of the 500.53s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.4/5.8 GB
	0.7838	 = Validation score   (f1_macro)
	26.72s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 473.73s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/5.9 GB
	Ensemble Weights: {'XGBoost': 0.429, 'LightGBMLarge': 0.286, 'RandomForestGini': 0.143, 'RandomForestEntr': 0.143}
	0.8055	 = Validation score   (f1_macro)
	0.21s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 126.95s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 18579.7 rows/s (1912 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/insujo/Documents/repo/orchestration/data/ai4i-split-v2/examples/ag-ai4i")

## 4. 앙상블 조합 만들기 (val 상위 TOP_K로 2 · 3개 조합)

In [4]:
lb = predictor.leaderboard(test, silent=True)
singles = lb[~lb["model"].str.startswith("WeightedEnsemble")].sort_values("score_val", ascending=False)
top = singles["model"].head(TOP_K).tolist()
print("조합에 쓸 모델:", top)
for r in (2, 3):
    for combo in combinations(top, r):
        suffix = "_" + "+".join(m.split("_")[0] for m in combo)
        predictor.fit_weighted_ensemble(base_models=list(combo), name_suffix=suffix)

Fitting model: WeightedEnsemble_L2_XGBoost+LightGBMLarge ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBMLarge': 0.6, 'XGBoost': 0.4}
	0.8034	 = Validation score   (f1_macro)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_XGBoost+LightGBM ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'XGBoost': 1.0}
	0.7996	 = Validation score   (f1_macro)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_XGBoost+CatBoost ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'XGBoost': 1.0}
	0.7996	 = Validation score   (f1_macro)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_LightGBMLarge+LightGBM ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBMLarge': 0.85, 'LightGBM': 0.15}
	0.7946	 = Validation score   (f1_macro)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_LightGBMLarge+CatBoost ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB

조합에 쓸 모델: ['XGBoost', 'LightGBMLarge', 'LightGBM', 'CatBoost']

	Ensemble Weights: {'LightGBMLarge': 1.0}
	0.7838	 = Validation score   (f1_macro)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_LightGBM+CatBoost ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBM': 1.0}
	0.7781	 = Validation score   (f1_macro)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_XGBoost+LightGBMLarge+LightGBM ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBMLarge': 0.6, 'XGBoost': 0.4}
	0.8034	 = Validation score   (f1_macro)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_XGBoost+LightGBMLarge+CatBoost ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBMLarge': 0.6, 'XGBoost': 0.4}
	0.8034	 = Validation score   (f1_macro)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_XGBoost+LightGBM+CatBoost ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'XGBoost': 1.0}
	0.7996	 = Validation score   (f1_macro)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_LightGBMLarge+LightGBM+CatBoost ...
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBMLarge': 0.778, 'LightGBM': 0.111, 'CatBoost': 0.111}
	0.8	 = Validation score   (f1_macro)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime

## 5. 비교표 — val 점수로 고르고, test는 확인만

In [5]:
lb = predictor.leaderboard(test, extra_metrics=["balanced_accuracy", "accuracy"], silent=True)
lb = lb.sort_values("score_val", ascending=False)
cols = ["model", "score_val", "score_test", "balanced_accuracy", "accuracy", "pred_time_test", "fit_time"]
lb[cols].to_csv("ag-ai4i-leaderboard.csv", index=False)
lb[cols]

,model,score_val,score_test,balanced_accuracy,accuracy,pred_time_test,fit_time
6,WeightedEnsemble_L2,0.805510,0.725363,0.776919,0.975967,0.123930,32.683630
7,WeightedEnsemble_L2_XGBoost+LightGBMLarge+LightGBM,0.803350,0.719750,0.766501,0.975967,0.022538,29.134318
8,WeightedEnsemble_L2_XGBoost+LightGBMLarge,0.803350,0.719750,0.766501,0.975967,0.022608,29.115669
9,WeightedEnsemble_L2_XGBoost+LightGBMLarge+CatBoost,0.803350,0.719750,0.766501,0.975967,0.022661,29.132536
2,WeightedEnsemble_L2_LightGBMLarge+LightGBM+CatBoost,0.800050,0.746444,0.746003,0.983804,0.044412,63.249773
11,XGBoost,0.799605,0.715951,0.775949,0.971264,0.015522,2.355970
12,WeightedEnsemble_L2_XGBoost+LightGBM+CatBoost,0.799605,0.715951,0.775949,0.971264,0.016068,2.411251
14,WeightedEnsemble_L2_XGBoost+CatBoost,0.799605,0.715951,0.775949,0.971264,0.016218,2.393074
13,WeightedEnsemble_L2_XGBoost+LightGBM,0.799605,0.715951,0.775949,0.971264,0.016095,2.393693
3,WeightedEnsemble_L2_LightGBMLarge+LightGBM,0.794630,0.744944,0.745788,0.982759,0.031417,34.542947
4,LightGBMLarge,0.783813,0.742380,0.756932,0.982236,0.006306,26.720813
5,WeightedEnsemble_L2_LightGBMLarge+CatBoost,0.783813,0.742380,0.756932,0.982236,0.006900,26.760655
0,LightGBM,0.778125,0.755085,0.733533,0.987461,0.024383,7.776802
1,WeightedEnsemble_L2_LightGBM+CatBoost,0.778125,0.755085,0.733533,0.987461,0.024870,7.818978
16,CatBoost,0.747494,0.681201,0.739167,0.980146,0.012875,28.697397
10,RandomForestEntr,0.731986,0.716094,0.738056,0.984326,0.049156,0.364528
18,NeuralNetTorch,0.731843,0.632582,0.560358,0.982759,0.009916,22.664590
19,NeuralNetFastAI,0.717396,0.627879,0.554558,0.981191,0.022878,14.614216
15,RandomForestGini,0.717030,0.707637,0.748043,0.982236,0.051695,3.033405
20,ExtraTreesGini,0.688952,0.584533,0.552957,0.979624,0.052128,0.375985
17,LightGBMXT,0.684209,0.639308,0.647290,0.979624,0.071390,18.491680
21,ExtraTreesEntr,0.682561,0.578784,0.551817,0.979624,0.056224,0.348909

In [6]:
best = lb.iloc[0]["model"]
print(f"val 1등: {best} — test {lb.iloc[0]['score_test']:.4f}")
if best.startswith("WeightedEnsemble"):
    print("앙상블이 쓴 모델:", list(predictor.info()["model_info"][best].get("children_info", {}).keys()))

val 1등: WeightedEnsemble_L2 — test 0.7254
앙상블이 쓴 모델: ['S1F1']

## 6. 1등 모델의 test 상세 (클래스별)

In [7]:
y_pred = predictor.predict(test, model=best)
print(pd.crosstab(test[TARGET], y_pred, rownames=["정답"], colnames=["예측"]))
predictor.evaluate(test, model=best, detailed_report=True)["classification_report"]

예측    HDF  NONE  OSF  PWF  TWF
정답
HDF    16     0    0    0    0
NONE    4  1821    5    2   23
OSF     0     4   11    0    0
PWF     0     1    0   18    0
TWF     0     7    0    0    2

{'HDF': {'precision': 0.8,
  'recall': 1.0,
  'f1-score': 0.8888888888888888,
  'support': 16.0},
 'NONE': {'precision': 0.9934533551554828,
  'recall': 0.9816711590296496,
  'f1-score': 0.987527114967462,
  'support': 1855.0},
 'OSF': {'precision': 0.6875,
  'recall': 0.7333333333333333,
  'f1-score': 0.7096774193548387,
  'support': 15.0},
 'PWF': {'precision': 0.9,
  'recall': 0.9473684210526315,
  'f1-score': 0.9230769230769231,
  'support': 19.0},
 'TWF': {'precision': 0.08,
  'recall': 0.2222222222222222,
  'f1-score': 0.11764705882352941,
  'support': 9.0},
 'accuracy': 0.9759665621734587,
 'macro avg': {'precision': 0.6921906710310965,
  'recall': 0.7769190271275673,
  'f1-score': 0.7253634810223285,
  'support': 1914.0},
 'weighted avg': {'precision': 0.9842155035597808,
  'recall': 0.9759665621734587,
  'f1-score': 0.9797949147570847,
  'support': 1914.0}}

## 메모
- 고르는 기준은 val. test로 고르면 마지막 평가가 부풀려짐
- val을 학습에 섞지 않음 — C1-a15 평가 카드(val 30 · test 30)의 출처
- 최종 모델은 ONNX로 넘김(D-237). 앙상블은 ONNX로 바꾸기 어려우니, 넘길 후보는 단일 트리 모델 등 바꿀 수 있는 것으로(추정)